# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 06:07
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reminder', '0003_subject_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqd_percent', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name=b'Required Percentage')),
                ('conducted', models.IntegerField(default=0)),
                ('attended', models.IntegerField(default=0)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='reminder.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
